# Generated by Django 4.2.4 on 2023-08-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='App1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Pass',
        ),
    ]
