# Generated by Django 4.2.4 on 2023-08-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_rename_email_app_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='name',
            new_name='email',
        ),
    ]
