# Generated by Django 4.2.4 on 2023-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_rename_name_app_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='App1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='app',
            name='password',
        ),
    ]
