# Generated by Django 4.2.4 on 2023-08-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_delete_app1_app_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='password',
            new_name='passwords',
        ),
    ]
