# Generated by Django 4.2.4 on 2023-08-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_rename_password_app_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='firstname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='lastname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='phonenumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
