# Generated by Django 4.2.4 on 2023-08-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_app_firstname_app_lastname_app_phonenumber_app_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='app',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
